# version: "3.7"
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80" # HTTP
            - "8443:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx:/etc/nginx/ssl
            - ../:/var/www:cached
        depends_on:
            - php
            - mysql
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ../:/var/www:cached
        # command: sh -c "chmod -R 777 /var/www && php-fpm"  # для wsl или linux
        depends_on:
            - mysql
            - redis
    mysql:
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    composer:
        image: composer:latest
        volumes:
            - ../:/app
        command: composer install --ignore-platform-reqs
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
volumes:
    mysqldata:
